### ISSUE TITLE
not loading/detecting tokens

### ISSUE THREAD

**Issue by eddo12321** [iLinked1337/OpenDiscordHaxx#2]
opendiscordhaxx's backend release and debug versions dont detect any tokens in the tokens.txt file, when going to the checker, it also says 0 valid 0 invalid 0/0, and it creates a tokens-Valid.txt with nothing in it.

**Comment by KadePcGames** [comment]
i've had this issue, but I'm pretty sure its because your tokens are invalid. Or marcus is a *baffoon*

**Comment by iLinked1337** [comment]
I'm pretty sure it's the first thing Kade said. Try the new 0.1 version, if it still doesn't work lmk
