### ISSUE TITLE
I Have checked all my token and it doesnt work

### ISSUE THREAD

**Issue by ybz7** [iLinked1337/OpenDiscordHaxx#3]
I have check all of my tokens and  none are invalid but still nothing happens when i try to use this someone help?

**Comment by SamYs94** [comment]
> I have check all of my tokens and none are invalid but still nothing happens when i try to use this someone help?

u nobp

**Comment by SamYs94** [comment]
noooooooob

**Comment by SamYs94** [comment]
why is this still open

**Comment by ybz7** [comment]
yes i am noob and i figured out how to do it bc im special thats why i didnt know before lol
