### ISSUE TITLE
when i open OpenDHBackend.exe, only an empty commands prompt named "OpenDHBackend.exe" opens

### ISSUE THREAD

**Issue by jack652** [iLinked1337/OpenDiscordHaxx#5]
title

**Comment by SamYs94** [comment]
u noob, u need open the index.html after that which is in the other folder, u prob didnt even read the ibsteuctions smh.

**Comment by NuKESec** [comment]
and you Sam need to learn proper English my guy

**Comment by jack652** [comment]
@SamYs94 i did both

**Comment by jack652** [comment]
my bad i thougt u had to raid from the command prompt opened
